# Generated by Django 4.0.2 on 2022-06-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_course_detail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course_detail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
