# Generated by Django 4.0.2 on 2022-06-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_is_active_course_detail_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_about',
            field=models.CharField(default='', help_text='Enter The Course Details At Least 20 Words', max_length=100),
            preserve_default=False,
        ),
    ]
