# Generated by Django 4.0.2 on 2022-06-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumcourse',
            options={'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='premiumcoursedetail',
            options={'verbose_name_plural': 'Course Detail'},
        ),
    ]
