# Generated by Django 4.0.2 on 2022-06-10 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premium', '0002_alter_premiumcourse_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(editable=False)),
                ('say_something', models.TextField(editable=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='premium.premiumcourse')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
